### ISSUE TITLE
Combining apostrophe make pynput crash: KeyError: "undefined character name 'COMBINING APOSTROPHE'"

### ISSUE THREAD

**Issue by adremides** [moses-palmer/pynput#150]
As I readed in another issue, "combining" part of the library is not finished. It crash because the name of the combination with the apostrophe is not 'COMBINING APOSTROPHE' but something like follows:
```
>>> unicodedata.name('á')
'LATIN SMALL LETTER A WITH ACUTE'
```

In order not to crash I replaced `self.combining = unicodedata.lookup('COMBINING ' + unicodedata.name(self.char))` with `self.combining = unicodedata.name(self.char)`. It works well with lowercase letters and combination characters like APOSTROPHE but not with TILDE (~) for example. I supose that is because the use of SHIFT to reach the character. When 'ñ' or 'Á' is tried to be writen, some character is missed by the library and the result of that is '`n' for the 'ñ' and just 'A' for 'Á'.

**Comment by SpecialCharacter** [comment]
Had the same problem with "combining ring above".

**Comment by TheRandomLabs** [comment]
I'm also having this issue:

```
Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\TheRandomLabs\.virtualenvs\MassiveMacro-RdDO-3rd\lib\site-packages\pynput\_util\__init__.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\TheRandomLabs\.virtualenvs\MassiveMacro-RdDO-3rd\lib\site-packages\pynput\keyboard\_win32.py", line 235, in _process
    key = self._event_to_key(msg, vk)
  File "C:\Users\TheRandomLabs\.virtualenvs\MassiveMacro-RdDO-3rd\lib\site-packages\pynput\keyboard\_win32.py", line 268, in _event_to_key
    msg in self._PRESS_MESSAGES))
  File "C:\Users\TheRandomLabs\.virtualenvs\MassiveMacro-RdDO-3rd\lib\site-packages\pynput\keyboard\_base.py", line 50, in __init__
    'COMBINING ' + unicodedata.name(self.char))
KeyError: "undefined character name 'COMBINING APOSTROPHE'"
```

**Comment by moses-palmer** [comment]
This error in relation to keyboard listeners is presumably solved by the upcoming version of _pynput_; I sorry for the long delay.

You may test it before release by cloning this repository and checking out [fixup-win32-keyboard-listener](https://github.com/moses-palmer/pynput/tree/fixup-win32-keyboard-listener).

I will now close this issue. @adremides, if your issue does not relate to keyboard listeners, please reopen.

**Comment by thierryjacoel** [comment]
I am still having the issue:
pynput version 1.5.2
Windows 10 pro
Keyboard setup with US International layout
