### ISSUE TITLE
`KeyError: "undefined character name 'COMBINING APOSTROPHE'"` In Listener with international keyboard

### ISSUE THREAD

**Issue by thierryjacoel** [moses-palmer/pynput#199]
I am using an international keyboard layout (I can write `é` using `' + e`, but I need to type `' + space` to produce a single `'`)
With a listener running, when typing the quote key, I get an error
```
Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\Thierry\Envs\vmo\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\Thierry\Envs\vmo\lib\site-packages\pynput\keyboard\_win32.py", line 266, in _process
    key = self._event_to_key(msg, vk)
  File "C:\Users\Thierry\Envs\vmo\lib\site-packages\pynput\keyboard\_win32.py", line 307, in _event_to_key
    msg in self._PRESS_MESSAGES))
  File "C:\Users\Thierry\Envs\vmo\lib\site-packages\pynput\keyboard\_base.py", line 53, in __init__
    'COMBINING ' + unicodedata.name(self.char))
KeyError: "undefined character name 'COMBINING APOSTROPHE'"
```

Which stops the listener.
Since this error happens in the decorator, I have no way of handling it in my code, and no way to prevent the Listener from stopping.

Windows 10
Pynput v1.5.2
International US keyboard layout

**Comment by moses-palmer** [comment]
Thank you for your report.

I have pushed a fix to [fixup-noncombining-dead-keys](https://github.com/moses-palmer/pynput/tree/fixup-noncombining-dead-keys). Is it possible for you to test?

**Comment by mtcool112** [comment]
@moses-palmer  I'm using pynput 1.6.8, but still get this error on my machine

``
    self.combining = unicodedata.lookup(
KeyError: "undefined character name 'COMBINING APOSTROPHE'"
``

Do you have any suggestions?

**Comment by mtcool112** [comment]
This is fixed in the following branch https://github.com/moses-palmer/pynput/tree/fixup-semidead-keys.

**Comment by moses-palmer** [comment]
This has now been fixed in *pynput 1.7.0*, so I will close this issue.
